// Drizzle schema. Tables land here in Phase 2 (PLAN.md): USER, VOLUNTEER_PROFILE,
// VOLUNTEER_SKILL, TEAM, TEAM_CAPABILITY, RESCUE_REQUEST, SELECTION, ASSIGNMENT,
// SCORING_WEIGHTS, AUDIT_ENTRY, SESSION.
export {};
